import numpy as np
from PIL import Image
import os
import matplotlib.pyplot as plt
import math
from PhaseMaskNorm import process_phase_mask
from bessel import generate_axicon_phase_mask

def calculate_bessel_beam_properties(
    slm_width_pixels,
    slm_height_pixels,
    pixel_pitch_um,
    wavelength_nm,
    bessel_cone_angle_degrees
):
    """
    Calculates the theoretical Depth of Field (DOF) and FWHM of the central lobe
    for a Bessel beam generated by an axicon on an SLM.

    Args:
        slm_width_pixels (int): The width of the SLM in pixels.
        slm_height_pixels (int): The height of the SLM in pixels.
        pixel_pitch_um (float): The physical size of each pixel on the SLM in micrometers.
        wavelength_nm (float): The wavelength of the incident light in nanometers.
        bessel_cone_angle_degrees (float): The desired half-cone angle of the Bessel beam
                                            in degrees.

    Returns:
        tuple: A tuple containing (dof_mm, fwhm_um).
               dof_mm (float): Theoretical Depth of Field in millimeters.
               fwhm_um (float): Theoretical FWHM of the central lobe in micrometers.
    """
    # Convert all units to meters for consistent calculations
    pixel_pitch_m = pixel_pitch_um * 1e-6 # um to m
    wavelength_m = wavelength_nm * 1e-9   # nm to m
    
    # Convert cone angle to radians
    alpha_rad = np.deg2rad(bessel_cone_angle_degrees)

    # Calculate the effective diameter of the illuminating beam on the SLM
    # Assuming the beam fills the smaller dimension of the SLM
    # For a circular beam, this would be the diameter of the circle.
    # For a rectangular SLM, it's often limited by the smaller side if the beam is circular.
    # If the beam overfills, it's the smaller SLM dimension.
    # If you have a specific beam diameter D that illuminates the SLM, use that instead.
    # Here, we assume the beam is shaped to fill the SLM's active area,
    # so the effective diameter is the smallest dimension of the SLM.
    D_m = min(slm_width_pixels, slm_height_pixels) * pixel_pitch_m

    # Ensure alpha_rad is not zero to avoid division by zero or tan(0) issues
    if alpha_rad == 0:
        raise ValueError("Bessel cone angle cannot be zero for DOF and FWHM calculation.")
    
    # Theoretical Depth of Field (DOF)
    # DOF = D / (2 * tan(alpha))
    dof_m = D_m / (2 * np.tan(alpha_rad))
    dof_mm = dof_m * 1e3 # Convert to millimeters

    # Theoretical FWHM of the Central Lobe
    # FWHM = 2.405 * lambda / (pi * sin(alpha))
    fwhm_m = (2.405 * wavelength_m) / (math.pi * np.sin(alpha_rad))
    fwhm_um = fwhm_m * 1e6 # Convert to micrometers

    return dof_mm, fwhm_um

# --- Main Script ---
if __name__ == "__main__":
    # --- SLM and Optical System Parameters ---
    slm_target_width = 1920
    slm_target_height = 1152
    slm_pixel_pitch_um = 9.2  # Example: Reflective SLM pixel pitch
    laser_wavelength_nm = 561.0 # Example: Green laser wavelength

    # --- Axicon Parameters ---
    axicon_resolution = (slm_target_height, slm_target_width) 
    desired_bessel_cone_angle_deg = 0.5 # Smaller angle for finer beam/longer DOF

    # --- Blazed Grating Parameters ---
    add_grating_overlay = True
    grating_x_period = 4
    grating_y_period = 0
    grating_angle = 0

    # --- Output File Path ---
    output_dir = "generated_phase_masks"
    os.makedirs(output_dir, exist_ok=True)
    output_axicon_with_grating_bmp = os.path.join(output_dir, "axicon_with_blazed_grating.bmp")
    output_axicon_only_bmp = os.path.join(output_dir, "axicon_only.bmp") # For comparison

    # --- Calculate and Print Theoretical Bessel Beam Properties ---
    print("\n--- Theoretical Bessel Beam Properties ---")
    theoretical_dof_mm, theoretical_fwhm_um = calculate_bessel_beam_properties(
        slm_width_pixels=slm_target_width,
        slm_height_pixels=slm_target_height,
        pixel_pitch_um=slm_pixel_pitch_um,
        wavelength_nm=laser_wavelength_nm,
        bessel_cone_angle_degrees=desired_bessel_cone_angle_deg
    )
    print(f"Theoretical Depth of Field (DOF): {theoretical_dof_mm:.2f} mm")
    print(f"Theoretical FWHM of Central Lobe: {theoretical_fwhm_um:.3f} um")
    print("------------------------------------------")

    print("\n--- Generating Axicon Phase Mask ---")
    axicon_phase_radians = generate_axicon_phase_mask(
        mask_resolution_pixels=axicon_resolution,
        pixel_pitch_um=slm_pixel_pitch_um,
        wavelength_nm=laser_wavelength_nm,
        bessel_cone_angle_degrees=desired_bessel_cone_angle_deg
    )

    print(f"Generated axicon phase mask (raw) shape: {axicon_phase_radians.shape}")
    print(f"Axicon phase values range: [{axicon_phase_radians.min():.4f}, {axicon_phase_radians.max():.4f}] radians")

    # --- Process Axicon ONLY (for comparison) ---
    print("\n--- Processing Axicon Mask WITHOUT Grating Overlay ---")
    process_phase_mask(
        input_phase_array=axicon_phase_radians,
        output_bmp_path=output_axicon_only_bmp,
        slm_width=slm_target_width,
        slm_height=slm_target_height,
        padding_mode=False,
        add_grating=False
    )
    print(f"Axicon only phase mask saved to: {output_axicon_only_bmp}")

    # --- Process Axicon with Blazed Grating Overlay ---
    print("\n--- Processing Axicon Mask WITH Blazed Grating Overlay ---")
    process_phase_mask(
        input_phase_array=axicon_phase_radians,
        output_bmp_path=output_axicon_with_grating_bmp,
        slm_width=slm_target_width,
        slm_height=slm_target_height,
        padding_mode=False,
        add_grating=add_grating_overlay,
        grating_period_x=grating_x_period,
        grating_period_y=grating_y_period,
        grating_angle_deg=grating_angle
    )
    print(f"Axicon with blazed grating phase mask saved to: {output_axicon_with_grating_bmp}")

    print("\n--- Visualization (Optional) ---")
    try:
        plt.figure(figsize=(8, 7))
        plt.imshow(axicon_phase_radians, cmap='hsv', origin='lower')
        plt.colorbar(label='Phase (radians)')
        plt.title('Generated Axicon Phase Mask (Raw)')
        plt.show()

        img_with_grating = Image.open(output_axicon_with_grating_bmp)
        plt.figure(figsize=(8, 7))
        plt.imshow(np.array(img_with_grating), cmap='gray', origin='lower')
        plt.colorbar(label='Grayscale Value (0-255)')
        plt.title('Axicon with Blazed Grating (8-bit BMP)')
        plt.show()

    except Exception as e:
        print(f"Matplotlib visualization failed. Ensure it is installed: {e}")